name: "Tests"

on: [pull_request]


jobs: 
    test:
        name: "Unit & E2E Test"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 2  
            - name: Setup PHP Action
              uses: shivammathur/setup-php@2.25.5
              with: 
                php-version: '8.0'
            - name: Install dependencies
              run: composer install --ignore-platform-reqs
            - name: Run Tests
              run:  composer test
              